// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"tour-guide-blog-backend/internal/model"
)

func newCarousel(db *gorm.DB, opts ...gen.DOOption) carousel {
	_carousel := carousel{}

	_carousel.carouselDo.UseDB(db, opts...)
	_carousel.carouselDo.UseModel(&model.Carousel{})

	tableName := _carousel.carouselDo.TableName()
	_carousel.ALL = field.NewAsterisk(tableName)
	_carousel.ID = field.NewUint(tableName, "id")
	_carousel.Title = field.NewString(tableName, "title")
	_carousel.ImageUrl = field.NewString(tableName, "image_url")
	_carousel.LinkUrl = field.NewString(tableName, "link_url")
	_carousel.SortOrder = field.NewInt(tableName, "sort_order")
	_carousel.IsActive = field.NewBool(tableName, "is_active")
	_carousel.CreatedAt = field.NewTime(tableName, "created_at")
	_carousel.UpdatedAt = field.NewTime(tableName, "updated_at")

	_carousel.fillFieldMap()

	return _carousel
}

type carousel struct {
	carouselDo

	ALL       field.Asterisk
	ID        field.Uint
	Title     field.String
	ImageUrl  field.String
	LinkUrl   field.String
	SortOrder field.Int
	IsActive  field.Bool
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (c carousel) Table(newTableName string) *carousel {
	c.carouselDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c carousel) As(alias string) *carousel {
	c.carouselDo.DO = *(c.carouselDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *carousel) updateTableName(table string) *carousel {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint(table, "id")
	c.Title = field.NewString(table, "title")
	c.ImageUrl = field.NewString(table, "image_url")
	c.LinkUrl = field.NewString(table, "link_url")
	c.SortOrder = field.NewInt(table, "sort_order")
	c.IsActive = field.NewBool(table, "is_active")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *carousel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *carousel) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 8)
	c.fieldMap["id"] = c.ID
	c.fieldMap["title"] = c.Title
	c.fieldMap["image_url"] = c.ImageUrl
	c.fieldMap["link_url"] = c.LinkUrl
	c.fieldMap["sort_order"] = c.SortOrder
	c.fieldMap["is_active"] = c.IsActive
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c carousel) clone(db *gorm.DB) carousel {
	c.carouselDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c carousel) replaceDB(db *gorm.DB) carousel {
	c.carouselDo.ReplaceDB(db)
	return c
}

type carouselDo struct{ gen.DO }

type ICarouselDo interface {
	gen.SubQuery
	Debug() ICarouselDo
	WithContext(ctx context.Context) ICarouselDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICarouselDo
	WriteDB() ICarouselDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICarouselDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICarouselDo
	Not(conds ...gen.Condition) ICarouselDo
	Or(conds ...gen.Condition) ICarouselDo
	Select(conds ...field.Expr) ICarouselDo
	Where(conds ...gen.Condition) ICarouselDo
	Order(conds ...field.Expr) ICarouselDo
	Distinct(cols ...field.Expr) ICarouselDo
	Omit(cols ...field.Expr) ICarouselDo
	Join(table schema.Tabler, on ...field.Expr) ICarouselDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICarouselDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICarouselDo
	Group(cols ...field.Expr) ICarouselDo
	Having(conds ...gen.Condition) ICarouselDo
	Limit(limit int) ICarouselDo
	Offset(offset int) ICarouselDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICarouselDo
	Unscoped() ICarouselDo
	Create(values ...*model.Carousel) error
	CreateInBatches(values []*model.Carousel, batchSize int) error
	Save(values ...*model.Carousel) error
	First() (*model.Carousel, error)
	Take() (*model.Carousel, error)
	Last() (*model.Carousel, error)
	Find() ([]*model.Carousel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Carousel, err error)
	FindInBatches(result *[]*model.Carousel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Carousel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICarouselDo
	Assign(attrs ...field.AssignExpr) ICarouselDo
	Joins(fields ...field.RelationField) ICarouselDo
	Preload(fields ...field.RelationField) ICarouselDo
	FirstOrInit() (*model.Carousel, error)
	FirstOrCreate() (*model.Carousel, error)
	FindByPage(offset int, limit int) (result []*model.Carousel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICarouselDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c carouselDo) Debug() ICarouselDo {
	return c.withDO(c.DO.Debug())
}

func (c carouselDo) WithContext(ctx context.Context) ICarouselDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c carouselDo) ReadDB() ICarouselDo {
	return c.Clauses(dbresolver.Read)
}

func (c carouselDo) WriteDB() ICarouselDo {
	return c.Clauses(dbresolver.Write)
}

func (c carouselDo) Session(config *gorm.Session) ICarouselDo {
	return c.withDO(c.DO.Session(config))
}

func (c carouselDo) Clauses(conds ...clause.Expression) ICarouselDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c carouselDo) Returning(value interface{}, columns ...string) ICarouselDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c carouselDo) Not(conds ...gen.Condition) ICarouselDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c carouselDo) Or(conds ...gen.Condition) ICarouselDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c carouselDo) Select(conds ...field.Expr) ICarouselDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c carouselDo) Where(conds ...gen.Condition) ICarouselDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c carouselDo) Order(conds ...field.Expr) ICarouselDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c carouselDo) Distinct(cols ...field.Expr) ICarouselDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c carouselDo) Omit(cols ...field.Expr) ICarouselDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c carouselDo) Join(table schema.Tabler, on ...field.Expr) ICarouselDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c carouselDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICarouselDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c carouselDo) RightJoin(table schema.Tabler, on ...field.Expr) ICarouselDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c carouselDo) Group(cols ...field.Expr) ICarouselDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c carouselDo) Having(conds ...gen.Condition) ICarouselDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c carouselDo) Limit(limit int) ICarouselDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c carouselDo) Offset(offset int) ICarouselDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c carouselDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICarouselDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c carouselDo) Unscoped() ICarouselDo {
	return c.withDO(c.DO.Unscoped())
}

func (c carouselDo) Create(values ...*model.Carousel) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c carouselDo) CreateInBatches(values []*model.Carousel, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c carouselDo) Save(values ...*model.Carousel) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c carouselDo) First() (*model.Carousel, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Carousel), nil
	}
}

func (c carouselDo) Take() (*model.Carousel, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Carousel), nil
	}
}

func (c carouselDo) Last() (*model.Carousel, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Carousel), nil
	}
}

func (c carouselDo) Find() ([]*model.Carousel, error) {
	result, err := c.DO.Find()
	return result.([]*model.Carousel), err
}

func (c carouselDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Carousel, err error) {
	buf := make([]*model.Carousel, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c carouselDo) FindInBatches(result *[]*model.Carousel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c carouselDo) Attrs(attrs ...field.AssignExpr) ICarouselDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c carouselDo) Assign(attrs ...field.AssignExpr) ICarouselDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c carouselDo) Joins(fields ...field.RelationField) ICarouselDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c carouselDo) Preload(fields ...field.RelationField) ICarouselDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c carouselDo) FirstOrInit() (*model.Carousel, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Carousel), nil
	}
}

func (c carouselDo) FirstOrCreate() (*model.Carousel, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Carousel), nil
	}
}

func (c carouselDo) FindByPage(offset int, limit int) (result []*model.Carousel, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c carouselDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c carouselDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c carouselDo) Delete(models ...*model.Carousel) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *carouselDo) withDO(do gen.Dao) *carouselDo {
	c.DO = *do.(*gen.DO)
	return c
}
