// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q        = new(Query)
	Admin    *admin
	Carousel *carousel
	Config   *config
	Contact  *contact
	Post     *post
	Review   *review
	Tour     *tour
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Admin = &Q.Admin
	Carousel = &Q.Carousel
	Config = &Q.Config
	Contact = &Q.Contact
	Post = &Q.Post
	Review = &Q.Review
	Tour = &Q.Tour
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:       db,
		Admin:    newAdmin(db, opts...),
		Carousel: newCarousel(db, opts...),
		Config:   newConfig(db, opts...),
		Contact:  newContact(db, opts...),
		Post:     newPost(db, opts...),
		Review:   newReview(db, opts...),
		Tour:     newTour(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Admin    admin
	Carousel carousel
	Config   config
	Contact  contact
	Post     post
	Review   review
	Tour     tour
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:       db,
		Admin:    q.Admin.clone(db),
		Carousel: q.Carousel.clone(db),
		Config:   q.Config.clone(db),
		Contact:  q.Contact.clone(db),
		Post:     q.Post.clone(db),
		Review:   q.Review.clone(db),
		Tour:     q.Tour.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:       db,
		Admin:    q.Admin.replaceDB(db),
		Carousel: q.Carousel.replaceDB(db),
		Config:   q.Config.replaceDB(db),
		Contact:  q.Contact.replaceDB(db),
		Post:     q.Post.replaceDB(db),
		Review:   q.Review.replaceDB(db),
		Tour:     q.Tour.replaceDB(db),
	}
}

type queryCtx struct {
	Admin    IAdminDo
	Carousel ICarouselDo
	Config   IConfigDo
	Contact  IContactDo
	Post     IPostDo
	Review   IReviewDo
	Tour     ITourDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Admin:    q.Admin.WithContext(ctx),
		Carousel: q.Carousel.WithContext(ctx),
		Config:   q.Config.WithContext(ctx),
		Contact:  q.Contact.WithContext(ctx),
		Post:     q.Post.WithContext(ctx),
		Review:   q.Review.WithContext(ctx),
		Tour:     q.Tour.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
