// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"tour-guide-blog-backend/internal/model"
)

func newTour(db *gorm.DB, opts ...gen.DOOption) tour {
	_tour := tour{}

	_tour.tourDo.UseDB(db, opts...)
	_tour.tourDo.UseModel(&model.Tour{})

	tableName := _tour.tourDo.TableName()
	_tour.ALL = field.NewAsterisk(tableName)
	_tour.ID = field.NewUint(tableName, "id")
	_tour.Title = field.NewString(tableName, "title")
	_tour.Description = field.NewString(tableName, "description")
	_tour.Content = field.NewString(tableName, "content")
	_tour.CoverImage = field.NewString(tableName, "cover_image")
	_tour.Price = field.NewFloat64(tableName, "price")
	_tour.Duration = field.NewString(tableName, "duration")
	_tour.Location = field.NewString(tableName, "location")
	_tour.CreatedAt = field.NewTime(tableName, "created_at")
	_tour.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tour.DeletedAt = field.NewField(tableName, "deleted_at")

	_tour.fillFieldMap()

	return _tour
}

type tour struct {
	tourDo

	ALL         field.Asterisk
	ID          field.Uint
	Title       field.String
	Description field.String
	Content     field.String
	CoverImage  field.String
	Price       field.Float64
	Duration    field.String
	Location    field.String
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field

	fieldMap map[string]field.Expr
}

func (t tour) Table(newTableName string) *tour {
	t.tourDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tour) As(alias string) *tour {
	t.tourDo.DO = *(t.tourDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tour) updateTableName(table string) *tour {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewUint(table, "id")
	t.Title = field.NewString(table, "title")
	t.Description = field.NewString(table, "description")
	t.Content = field.NewString(table, "content")
	t.CoverImage = field.NewString(table, "cover_image")
	t.Price = field.NewFloat64(table, "price")
	t.Duration = field.NewString(table, "duration")
	t.Location = field.NewString(table, "location")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")

	t.fillFieldMap()

	return t
}

func (t *tour) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tour) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 11)
	t.fieldMap["id"] = t.ID
	t.fieldMap["title"] = t.Title
	t.fieldMap["description"] = t.Description
	t.fieldMap["content"] = t.Content
	t.fieldMap["cover_image"] = t.CoverImage
	t.fieldMap["price"] = t.Price
	t.fieldMap["duration"] = t.Duration
	t.fieldMap["location"] = t.Location
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
}

func (t tour) clone(db *gorm.DB) tour {
	t.tourDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tour) replaceDB(db *gorm.DB) tour {
	t.tourDo.ReplaceDB(db)
	return t
}

type tourDo struct{ gen.DO }

type ITourDo interface {
	gen.SubQuery
	Debug() ITourDo
	WithContext(ctx context.Context) ITourDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITourDo
	WriteDB() ITourDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITourDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITourDo
	Not(conds ...gen.Condition) ITourDo
	Or(conds ...gen.Condition) ITourDo
	Select(conds ...field.Expr) ITourDo
	Where(conds ...gen.Condition) ITourDo
	Order(conds ...field.Expr) ITourDo
	Distinct(cols ...field.Expr) ITourDo
	Omit(cols ...field.Expr) ITourDo
	Join(table schema.Tabler, on ...field.Expr) ITourDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITourDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITourDo
	Group(cols ...field.Expr) ITourDo
	Having(conds ...gen.Condition) ITourDo
	Limit(limit int) ITourDo
	Offset(offset int) ITourDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITourDo
	Unscoped() ITourDo
	Create(values ...*model.Tour) error
	CreateInBatches(values []*model.Tour, batchSize int) error
	Save(values ...*model.Tour) error
	First() (*model.Tour, error)
	Take() (*model.Tour, error)
	Last() (*model.Tour, error)
	Find() ([]*model.Tour, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Tour, err error)
	FindInBatches(result *[]*model.Tour, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Tour) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITourDo
	Assign(attrs ...field.AssignExpr) ITourDo
	Joins(fields ...field.RelationField) ITourDo
	Preload(fields ...field.RelationField) ITourDo
	FirstOrInit() (*model.Tour, error)
	FirstOrCreate() (*model.Tour, error)
	FindByPage(offset int, limit int) (result []*model.Tour, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITourDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tourDo) Debug() ITourDo {
	return t.withDO(t.DO.Debug())
}

func (t tourDo) WithContext(ctx context.Context) ITourDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tourDo) ReadDB() ITourDo {
	return t.Clauses(dbresolver.Read)
}

func (t tourDo) WriteDB() ITourDo {
	return t.Clauses(dbresolver.Write)
}

func (t tourDo) Session(config *gorm.Session) ITourDo {
	return t.withDO(t.DO.Session(config))
}

func (t tourDo) Clauses(conds ...clause.Expression) ITourDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tourDo) Returning(value interface{}, columns ...string) ITourDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tourDo) Not(conds ...gen.Condition) ITourDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tourDo) Or(conds ...gen.Condition) ITourDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tourDo) Select(conds ...field.Expr) ITourDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tourDo) Where(conds ...gen.Condition) ITourDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tourDo) Order(conds ...field.Expr) ITourDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tourDo) Distinct(cols ...field.Expr) ITourDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tourDo) Omit(cols ...field.Expr) ITourDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tourDo) Join(table schema.Tabler, on ...field.Expr) ITourDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tourDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITourDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tourDo) RightJoin(table schema.Tabler, on ...field.Expr) ITourDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tourDo) Group(cols ...field.Expr) ITourDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tourDo) Having(conds ...gen.Condition) ITourDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tourDo) Limit(limit int) ITourDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tourDo) Offset(offset int) ITourDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tourDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITourDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tourDo) Unscoped() ITourDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tourDo) Create(values ...*model.Tour) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tourDo) CreateInBatches(values []*model.Tour, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tourDo) Save(values ...*model.Tour) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tourDo) First() (*model.Tour, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Tour), nil
	}
}

func (t tourDo) Take() (*model.Tour, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Tour), nil
	}
}

func (t tourDo) Last() (*model.Tour, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Tour), nil
	}
}

func (t tourDo) Find() ([]*model.Tour, error) {
	result, err := t.DO.Find()
	return result.([]*model.Tour), err
}

func (t tourDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Tour, err error) {
	buf := make([]*model.Tour, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tourDo) FindInBatches(result *[]*model.Tour, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tourDo) Attrs(attrs ...field.AssignExpr) ITourDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tourDo) Assign(attrs ...field.AssignExpr) ITourDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tourDo) Joins(fields ...field.RelationField) ITourDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tourDo) Preload(fields ...field.RelationField) ITourDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tourDo) FirstOrInit() (*model.Tour, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Tour), nil
	}
}

func (t tourDo) FirstOrCreate() (*model.Tour, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Tour), nil
	}
}

func (t tourDo) FindByPage(offset int, limit int) (result []*model.Tour, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tourDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tourDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tourDo) Delete(models ...*model.Tour) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tourDo) withDO(do gen.Dao) *tourDo {
	t.DO = *do.(*gen.DO)
	return t
}
