export const HOME_HERO_IMAGE_WIDTH = 1920;
export const HOME_HERO_IMAGE_HEIGHT = 720;
export const HOME_HERO_IMAGE_RATIO = HOME_HERO_IMAGE_WIDTH / HOME_HERO_IMAGE_HEIGHT;
export const HOME_HERO_IMAGE_OBJECT_POSITION = 'center top';
